server:
  port: 2002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/oauth
  profiles:
    active: dev
  application:
    name: OAUTH2
  cloud:
    nacos:
      config:
        file-extension: yml
        shared-configs:
          - ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      discovery:
        server-addr: 192.168.1.73:8848